# Generated by Django 5.2.3 on 2025-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
